# =====================================================
# Atlas Spark Lab
# Global Spark Configuration
# =====================================================

# Enable Spark Event Logs
spark.eventLog.enabled                     true

# Directory where Drivers write Event Logs
spark.eventLog.dir                         file:/opt/spark-events

# History Server reads logs from this directory
spark.history.fs.logDirectory              file:/opt/spark-events

# Compress Event Logs
spark.eventLog.compress                    true